theme: jekyll-theme-cayman
# theme: minima

# Do not show repo readme in header of index file
exclude: ['./README.md']

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
